### ISSUE TITLE
Re-organize Types into separate branches

### ISSUE THREAD

**Issue by danielwrobert** [Automattic/theme-pattern-library#83]
After working with @davidakennedy to build out the zip file generator on components.underscores.me, we began talking about how we can also continue to use the CLI (Slush) generator for those who prefer that option.

Currently, as things are structured, this is would be quite difficult. A lot would have to change between the template files that are served to the Slush generator and the actual repo files that make up the Theme Pattern Library.

I've been thinking a good amount over the weekend about the structure of the Theme Pattern Library repo.

I believe, after working through the UI generator with @davidakennedy and considering the CLI generator, pulling the Types out into their own branch may be a better approach. This structure would allow us to use the repository with different generators (UI & CLI). I also believe that doing this would make contribution efforts more straightforward, while also making maintenance of the generators a more simple process.

As it stands, the zip generating functionality in components.underscores.me contains a good amount of hard-coded file paths. This was necessary because of the way the Theme Pattern Library is currently set up (which made perfect sense up until this point, I will add). Each Type is a build off of the Base Type and the differing files live in the Types folder broken up by each type. This means that, in order to generate a zip for each type, we needed to run through the Types directory, copy over/replace the needed folders and files for the requested type and then delete the Types folder in a cleanup process.

All of this processing functionality would be unnecessary if we move out the different types into branches of their own. We would then be able to request a zip download from that particular branch, unzip it and find/replace the user-input project name strings throughout the project. The CLI generator has a similar complexity, based on the current structure, that could then be simplified.

I believe that contributing and adding new branches would be easier this way as well. We, or a contributor, would simply create a new branch from the master branch and add the files for that new Type.

The only manual work at that point would be to add a new section (and robot) for the new types on components.underscores.me and to add a new button option for the generator.

With regards to the repository workflow, we could still follow a similar "Git Flow" structure with "feature-" and "hotfix-" prefixed branches. Each type branch could be prefixed with "type-" (type-portfolio, for example).

Considering these things, I feel that there a handful of compelling reasons to move the Types to their own branches and not many reasons not to. I could be overlooking some good arguments against this so I'd love to hear your thoughts as well!

**Comment by danielwrobert** [comment]
See [related issue](https://github.com/Automattic/components.underscores.me/issues/55) on components.underscores.me repository. If/when this issue is updated, generator code in that repo will need to be refactored.

**Comment by sarahmonster** [comment]
I love this idea and would be totally into it. My biggest concern would be: how do we deal with PRs that affect files in multiple types? Is there an easier way of handling this?

For example, I recently did a PR to mirror a change in _s:

_s: https://github.com/Automattic/_s/pull/776/files
pattern library: https://github.com/Automattic/theme-pattern-library/pull/82/files

Making the same change across pattern library files was more time-consuming, and affected more files (11 rather than 5 for a relatively simple change) and I wasn't 100% certain I'd caught everything. The increased complexity of the file structure already makes it a bit more intimidating trying to submit a pull request. My concern is that if *we* find it intimidating, others may as well.

Will splitting the types into branches make changes like this more or less difficult? Is there a way we can structure the library so it's still "component-ized" but more straightforward to maintain and contribute to?

**Comment by danielwrobert** [comment]
Excellent points!

I believe this is a tradeoff here, to some degree. I don't believe there is a perfect solution. This was actually something that @davidakennedy discussed when I mentioned this idea to him the other day.

For changes that affect files in multiple Types, I think the best approach would be to make that change in Master or Base, locally, and then merge over from that branch (as all of the Types have these base files). Alternatively, if the changes are not in base but in more than one of the Types branches, you may need to make those individual changes per each branch, locally, and push those changes up for a PR. That said, we will need to be a little more aware when reviewing PRs.

So in the case of your example, I think it certainly adds an extra step or two - which isn't ideal. But I do believe it is a good tradeoff _overall_, as everything else will be more manageable and, _I think_, a bit more clear. As long as we keep our branches organized and the project well documented. I also believe that using branches here offers us a lot more flexibility and the ability to greatly simplify our code.

Looking at a project like Calypso, which also has a lot of branches, is a great example of structural repo organization.

**Comment by sarahmonster** [comment]
The branch solution sounds like it might be the most elegant option here. It would be extremely helpful—I think to all of us who aren't super-familiar with the project—to have a sense of how the file structure works. I think this would be helpful, not just for *our* understanding of the project, but for potential contributors as well. 

Clear, understandable documentation is a big step toward getting us there. 

I'd love to see a PR for this—or even a diagram mocking up structure—so we can all get a better sense of how all the pieces will fit together...

**Comment by davidakennedy** [comment]
Yeah, as @danielwrobert mentioned, I have some of the same concerns as you do, @sarahmonster, but I think we can manage most of it with a clear Wiki page with documentation.

I think this is one of those cases where the maintainers of a project need to do a bit more work in order to make it easier on potential contributors and current contributors to pitch in. :smile: In this case, we want it to be easy to see types on their own, add to types, and potentially propose new types when appropriate. I don't think that will happen a lot, but it's nice to know it will be easier.

**Comment by sarahmonster** [comment]
> I think this is one of those cases where the maintainers of a project need to do a bit more work in order to make it easier on potential contributors and current contributors to pitch in.

Absolutely agree. My biggest concern with this project as a whole is that it might be less accessible to contributors. I think everything we can do to ease the path to contribution—even if that means more work maintaining, documenting, and reviewing on our end—will make the project more impactful.

**Comment by karmatosed** [comment]
I totally get the reasons for, but I feel this isn't a good decision. It feels a 'devcentric' option and that is concerning.There are several reasons why I think this. For now going to just put them out and we can discuss.

- I do not agree this makes contributions easier. Having in branches not only hides the types but it also makes contributing harder. You are very much hiding something. I take the point about documentation, but adding more documentation to fix a hurdle you make isn't good practice.
- In putting into branches you are using branches unlike any projects do. Or any I know of. Could you provide examples of projects that use branches like this? I think it's a valid point that people expect branches to be one thing and it's being suggested they are another. A branch is a commit split to a lot of people and this isn't what you are doing here. Types will never merge or be removed as a branch.
- Contributor confusion from existing contributors (me) is there already as to this method. It feels very clunky and not at all like it makes things clearer. Let alone how someone then does PR and issues. This is just going to spiral.
- It's hiding a part of the project in a branch. This segments it when it's not an isolated part. It is part of this project not a branch.

With all those points raised, lets pan out a bit. There doesn't seem to be an initially absolutely ok option. In that case, we should find the one of least friction and not just dive in. We should also consider what we are trying to achieve and why we need to change things. It's important to focus in on why this issue is being done and perhaps what alternatives are there to branching. I don't see alternatives being offered, just that branching is the only way. Is it? What other ways could be done that provide both a better structure, user, contributor experience and also the benefits being sought for the generators?

I only have one initial idea but we should look to brainstorm others:
- Move types to a new repo. This does make some sense from a repo point of view to have a base then the types. It's clunky still but avoids the problematic use of branches. This still causes the issue of hiding part of the project but it makes sense for other logic.

**Comment by karmatosed** [comment]
Adding note here that the more I think about it the more types could easily fit in a different repo. It plays on the plugin suite idea that a lot use. Worth as speculation as to if this works for the generator.

**Comment by davidakennedy** [comment]
We discussed this as a team and decided to move forward with the branches approach.
